#!/bin/sh
# Emit the Homebrew formula for a release on stdout, with download URLs and
# checksums taken from the release's SHA256SUMS file.
#
# Usage: scripts/release/brew-formula.sh <version> <SHA256SUMS> > spice.rb
set -eu

version="$1"
sums="$2"

sha_for() {
  sha="$(awk -v f="spice-$1.tar.gz" '$2 == f { print $1 }' "$sums")"
  if [ -z "$sha" ]; then
    echo "brew-formula.sh: no checksum for spice-$1.tar.gz in $sums" >&2
    exit 1
  fi
  printf '%s' "$sha"
}

base="https://github.com/invariant-hq/spice/releases/download/$version"

cat <<EOF
# Generated by scripts/release/brew-formula.sh; do not edit by hand.
class Spice < Formula
  desc "OCaml coding agent"
  homepage "https://github.com/invariant-hq/spice"
  version "$version"
  license "ISC"

  on_macos do
    on_arm do
      url "$base/spice-darwin-arm64.tar.gz"
      sha256 "$(sha_for darwin-arm64)"
    end
    on_intel do
      url "$base/spice-darwin-x64.tar.gz"
      sha256 "$(sha_for darwin-x64)"
    end
  end

  on_linux do
    on_arm do
      url "$base/spice-linux-arm64.tar.gz"
      sha256 "$(sha_for linux-arm64)"
    end
    on_intel do
      url "$base/spice-linux-x64.tar.gz"
      sha256 "$(sha_for linux-x64)"
    end
  end

  def install
    bin.install "spice"
    generate_completions_from_executable(bin/"spice", "completion",
                                         shells: [:bash, :zsh])
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/spice --version").strip
  end
end
EOF
